#!/usr/bin/env python3.10
"""Provide the command-line interface."""
import argparse
import norlunda as nl


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Apply a Norlunda sound change to a Proto-Germanic root word."
    )
    parser.add_argument(
        "--words",
        metavar="W",
        nargs="+",
        help="words to apply the change to (incompatible with --file)",
    )
    # parser.add_argument(
    #     "--file",
    #     type=p.Path,
    #     help="a JSON file containing the words to apply the sound change to (pass -) for stdin",
    # )

    args = parser.parse_args()
    k = map(nl.soundchanges, args.words)
    print(" ".join(k))


if __name__ == "__main__":
    main()
